### ISSUE TITLE
No hints how to use it, outdated for Wordpress 6.0.1

### ISSUE THREAD

**Issue by horshack** [lcashdol/wp-login-logger#1]
There should be a little hint in which version of wordpress this can be used. 

I tried to simply copy the file wp-admin.php into my theme in Wordpress 6.0.1, this did not work.

**Comment by horshack** [comment]
I think the new way to log failed attempts to login is to use a wordpress hook.

# Log failed login attempts

I have a lot of failed logins to a wordpress-admin-webpage. I want to know which
login-name gets abused and which passwords the attackers use.

First thought was to manipulate wordpress' loginpage. But the cool people at wordpress
thought about a way which is much better. They are calling hooks for a lot of actions
wordpress is doing. These hooks are documented here:

* https://developer.wordpress.org/reference/hooks


## Preparation: create a child theme

Create a child theme of Divi (this is the theme I use). There is an explanation
how to do this here:

* https://www.elegantthemes.com/blog/divi-resources/divi-child-theme


## Write a custom functions for logging failed login attempts

My child theme is in Directory ~www-data/wpmyblog/wwwroot/wordpress/wp-content/themes/divi-child-li

There are only these files in the directory

```
-rw-r--r-- 1 www-data www-data 1144 Aug  5 07:32 functions.php
-rw-r--r-- 1 www-data www-data  368 Aug  5 07:29 style.css
```

In the file functions.php I do this:

```
<?php

# Sources of information
#
# Hooks:
#    https://developer.wordpress.org/reference/hooks/wp_login/
# What to log:
#    https://github.com/lcashdol/wp-login-logger/blob/master/wp-admin.php
function log_error_logins( $user_login, $error ) {
    $log_file = "/var/www/wpmyblog/logs/failed_logins.log";
    $ip       = $_SERVER['REMOTE_ADDR'];
    $logdate  = date(DATE_RFC2822);
    $login    = $_POST['log'];
    $password = $_POST['pwd'];
    $redirect = $_POST['redirect_to'];
    $data     = "===================================[Event $logdate Notice for $ip]=======================================\n";
    $data .= "Login:" . $login . "\n";
    $data .= "Password:" . $password . "\n";
    $data .= "Redirect:" . $redirect . "\n";
    foreach (getallheaders() as $name => $value) {
        $data .= "$name: $value\n";
    }
    $data .= "===========================================[Event End]============================================\n";
    file_put_contents($log_file, "text", FILE_APPEND | LOCK_EX);
    file_put_contents($log_file, $data, FILE_APPEND | LOCK_EX);
}
add_action('wp_login_failed', 'log_error_logins', 10, 2);
```

Don't forget to create the logging-directory writable to the webserver-user.

**Comment by lcashdol** [comment]
Ah, I'm sorry. Yes, this code is very out of date.
